/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rest.framework

import kotlin.collections.*

class HttpMethod(string: String) {
	companion object {
		val get = HttpMethod("get")
		val post = HttpMethod("post")
	}
}

class Endpoint<T>(path: String){
	private val PATH_START = "root/"
	val path = PATH_START + path

	val map: MutableMap<HttpMethod, ()->Response<*>?> = mutableMapOf()

	fun recieveGet(): Response<T>? {
		val lambda = map.get(HttpMethod.get) as ()->Response<T>
		return lambda()
	}

	fun recievePost(): Response<String>? {
		val lambda = map.get(HttpMethod.post) as ()->Response<String>
		return lambda()
	}

	fun get(lambda: ()->Response<T>? ) {
		map.put(HttpMethod.get, lambda)
	}

	fun post(lambda: ()->Response<String>? ) {
		map.put(HttpMethod.post, lambda)
	}
}


class Request(rawData: Int?) {
}

class Response<T>(public val data: T? = null) {
	companion object {
		fun <U> response201(message: U):Response<U>? {
			return Response(message)
		}
		fun <U> response200(character: U?):Response<U>? {
			return Response(character)
		}
	}
}

class WebClient {
}

class WebServer(val path: String, val client: WebClient?) {
	fun start() {
		//val incoming = client?.listen()
		//val request = Request(incoming)
		//val response = responseFor<Character>(request)
		//client?.respond(response)
	}
	
	fun <T> responseFor(request: Request?): Response<T>? {
		return null
	}

	fun addEndpoint(endpoint: Endpoint<Character>) {
	}
}

fun main() {
}

